urls.py
from registration import *
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.generic.simple import direct_to_template

admin.autodiscover()

urlpatterns = patterns('',
	# Default
	(r'^$', 'posts.views.index'),
	(r'^users/.+$', 'posts.views.index'),

	# Posts
	(r'^posts/$', 'posts.views.index'),
	(r'^posts/new$', 'posts.views.add'),
	(r'^posts/(?P<post_id>\d+)/$', 'posts.views.detail'),
	(r'^posts/(?P<post_id>\d+)/edit$', 'posts.views.edit'),
	(r'^posts/(?P<post_id>\d+)/delete$', 'posts.views.delete'),
	(r'^posts/(?P<post_id>\d+)/reply$', 'posts.views.reply'),
	(r'^posts/(?P<post_id>\d+)/reply/(?P<reply_id>\d+)/$', 'posts.views.reply'),
	(r'^posts/(?P<post_id>\d+)/reply/(?P<reply_id>\d+)/delete$', 'posts.views.reply_delete'),

 	# url(r'^$', 'jobshaker.views.home', name='home'),
	# url(r'^jobshaker/', include('jobshaker.foo.urls')),

	# Profile
	(r'^userprofile/(?P<userprofile_id>\d+)/$', 'posts.views.profile'),	
	(r'^userprofile/replies/$', 'posts.views.my_replies'),
	(r'^userprofile/$', 'posts.views.my_profile'),
	(r'^accounts/profile/$', 'posts.views.my_profile'),
	(r'^accounts/profile/(?P<user_id>\d+)/$', 'posts.views.user'),
	(r'^accounts/edit/$', 'posts.views.edit_profile'),
	#(r'^users/(?P<user_username>\d+)/$', 'users.views.detail'),

	# Login form
	(r'^login/$', 'django.contrib.auth.views.login', 
		{'template_name': 'registration/login.html'}),
		
	# Registration form
	(r'^accounts/', include('registration.backends.simple.urls')),
	
	# Static pages
	('^about/$',  direct_to_template, { 'template': 'pages/about.html'}),
	('^links/$',  direct_to_template, { 'template': 'pages/links.html'}),
	('^policy/$', direct_to_template, { 'template': 'pages/privacy.html'}),
	
	# Uncomment the admin/doc line below to enable admin documentation:
	# url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	
	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
)

posts/models.py
from django.db import models
from django.contrib import auth
from taggit.managers import TaggableManager
import datetime
	
class UserProfile(models.Model):
	user = models.OneToOneField(auth.models.User)
	profession = models.CharField(max_length=30)
	postcode = models.PositiveIntegerField()
	english = models.BooleanField()
	german = models.BooleanField()
	french = models.BooleanField()
	italian = models.BooleanField()
	other_lang = models.CharField('Other', max_length=70, blank=True, null=True)
	birth_year = models.PositiveIntegerField('Year of birth', blank=True, null=True)
	GENDER_CHOICES = (
	        (u'M', u'Male'),
	        (u'F', u'Female'),
	    )
	sex = models.CharField(max_length=2, choices=GENDER_CHOICES, blank=True, null=True)
	aboutme = models.TextField('About myself', max_length=500, blank=True, null=True)
	def __unicode__(self):
		return self.user.username

class Intent(models.Model):
	name = models.CharField(max_length=70)
	icon = models.CharField(max_length=99, blank=True, null=True)
	back = models.CharField(max_length=99, blank=True, null=True)
	def __unicode__(self):
		return self.name
		
class Post(models.Model):
	pub_date = models.DateTimeField('date published', auto_now_add=True)
	user = models.ForeignKey(UserProfile, editable=False)
	intent = models.ForeignKey(Intent)
	location = models.CharField(max_length=60, blank=True, null=True)
	valid_from = models.DateField(blank=True, null=True) 
	valid_until = models.DateField(blank=True, null=True) 
	tags = TaggableManager()
	comment = models.TextField()
	def __unicode__(self):
		return self.intent.name
	def was_published_today(self):
		return self.pub_date.date() == datetime.date.today()
	class Meta:
		ordering = ['-pub_date', 'location']
	
class Reply(models.Model):
	pub_date = models.DateTimeField('date replied', auto_now_add=True)
	user = models.ForeignKey(UserProfile, editable=False)
	post = models.ForeignKey(Post, editable=False)
	reply_to = models.ForeignKey('self', related_name='replies', 
		editable=False, null=True, blank=True)
	# flag = models.BooleanField()
	# like = models.BooleanField()
	comment = models.TextField()
	def __unicode__(self):
		return self.comment
	class Meta:
		ordering = ['pub_date']

posts/forms.py
from django import forms
from posts.models import *

def make_custom_datefield(f):
    formfield = f.formfield()
    if isinstance(f, models.DateField):
        formfield.widget.format = '%m/%d/%Y'
        formfield.widget.attrs.update({'class':'datePicker', 'readonly':'true'})
    return formfield
    
class PostForm(forms.ModelForm):
    formfield_callback = make_custom_datefield
    class Meta:
        model = Post
        exclude = ['user', 'pub_date']

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        exclude = ['pub_date']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['user']
    # TODO: validate postcode (1000 - 9999)
    # TODO: validate birth year
    #class clean_birth_year(self):
		#	if self and (self < 1910 or self > 2010):
		#		raise forms.ValidationError('Invalid birth year')

posts/views.py
from django.shortcuts import redirect, render_to_response, get_object_or_404
from django.template import RequestContext
from django.contrib import messages
from django.http import Http404
from datetime import date

from information.models import *
from posts.models import *
from posts.forms import *

# Home page
def index(request):
	if request.user.id:
		try:
			up = UserProfile.objects.get(user=request.user.id)
		except UserProfile.DoesNotExist:
			return edit_profile(request)
	latest_post_list = Post.objects.all().order_by('-pub_date')[:30]
	return render_to_response('posts/index.html', {
		'latest_post_list': latest_post_list,
		'is_at_home': True
	}, context_instance=RequestContext(request))

# Post detail
def detail(request, post_id):
	try:
		up = UserProfile.objects.get(user=request.user.id)
		p = Post.objects.get(pk=post_id)
		l_user = l_post = ''
		if p.user.postcode:
			l_user = get_location_by_plz(p.user.postcode)
	except Post.DoesNotExist:
		raise Http404
	return render_to_response('posts/detail.html', {
			'post': p, 'where': p.location, 'place': l_user, 
			'replies': Reply.objects.filter(post=p), 
			'my_post': (p.user.id == up.id),
			'user_id': up.id
		}, context_instance=RequestContext(request))

# Add new post
def add(request):
	up = UserProfile.objects.get(user=request.user.id)
	form = PostForm(request.POST or None)
	if form.is_valid():
		post = form.save(commit=False)
		post.user_id = up.id
		post.save()
		form.save_m2m() # Saves tags
		messages.success(request, 'Thanks for posting!')
		return redirect('/posts/%d' % post.id)
	form.initial['postcode'] = up.postcode
	return render_to_response('posts/edit_post.html', {
			'form': form
		}, context_instance=RequestContext(request))
	
# Edit a post
def edit(request, post_id):
	up = UserProfile.objects.get(user=request.user.id)
	post = get_object_or_404(Post, id=post_id)
	form = PostForm(request.POST or None, instance=post)
	if form.is_valid():
		post = form.save(commit=False)
		post.user_id = up.id
		post.save()
		form.save_m2m() # Saves tags
		messages.success(request, 'Your post has been saved.')
		return redirect('/posts/%d' % post.id)
	return render_to_response('posts/edit_post.html', {
			'form': form, 'post': post
		}, context_instance=RequestContext(request))

# Delete (TODO: archive) a post
def delete(request, post_id):
	up = UserProfile.objects.get(user=request.user.id)
	post = get_object_or_404(Post, id=post_id)
	form = PostForm(request.POST or None, instance=post)
	if post.user_id == up.id:
		post.delete()
		messages.success(request, 'Your post has been removed.')
	return redirect('/')

# Replies to post
def reply(request, post_id, reply_id=-1):
	try:
		up = UserProfile.objects.get(user=request.user.id)
		p = Post.objects.get(pk=post_id)
		r = None
		if reply_id > -1:
			r = Reply.objects.get(pk=reply_id)
	except UserProfile.DoesNotExist:
		return edit_profile(request)
	form = ReplyForm(request.POST or None)
	if form.is_valid():
		reply = form.save(commit=False)
		reply.user_id = up.id
		reply.post_id = p.id
		if r != None:
			reply.reply_to = r
		reply.save()
		messages.success(request, 'Your message was sent.')
		return redirect('/posts/%d' % p.id)
	return render_to_response('posts/edit_reply.html', {
			'post': p, 'form': form
		}, context_instance=RequestContext(request))

# Delete a reply
def reply_delete(request, post_id, reply_id):
	try:
		up = UserProfile.objects.get(user=request.user.id)
		p = Post.objects.get(pk=post_id)
		r = Reply.objects.get(pk=reply_id)
	except UserProfile.DoesNotExist:
		return edit_profile(request)
	if p.user_id == up.id or r.user_id == up.id:
		r.delete()
		messages.success(request, 'Your reply was deleted.')
	return redirect('/posts/%d' % p.id)
		
# View my profile
def my_profile(request):
	try:
		up = UserProfile.objects.get(user=request.user.id)
		return profile(request, up.id)
	except UserProfile.DoesNotExist:
		return edit_profile(request)

# View my replies
def my_replies(request):
	try:
		up = UserProfile.objects.get(user=request.user.id)
		myposts = Post.objects.filter(user=up)
		replies = Reply.objects.filter(post__user=up)
		myreplies = Reply.objects.select_related().filter(user=up)
		replypostsdict = {}
		replyposts = []
		for r in myreplies:
			if not r.post.id in replypostsdict and r.post.user != up:
				replypostsdict[r.post.id] = True
				replyposts.append(r.post)
		return render_to_response('user/replies.html', {
				'userprofile': up,
				'myposts': myposts, 'replies': replies, 
				'replyposts': replyposts, 'myreplies': myreplies
			}, context_instance=RequestContext(request))
	except UserProfile.DoesNotExist:
		return edit_profile(request)

# View a profile		
def profile(request, userprofile_id):
	up = get_object_or_404(UserProfile, pk=userprofile_id)
	if up.postcode:
		user_location = get_location_by_plz(up.postcode)
	user_languages = ''
	user_age = ''
	if up.german:
		user_languages += 'German, '
	if up.french:
		user_languages += 'French, '
	if up.italian:
		user_languages += 'Italian, '
	if up.english:
		user_languages += 'English, '
	if up.other_lang:
		user_languages += up.other_lang
	elif user_languages != '':
		user_languages = user_languages[:-2]
	if up.birth_year:
		user_age = date.today().year - up.birth_year - 1
	return render_to_response('user/detail.html', {
			'userprofile': up, 'location': user_location,
			'languages': user_languages, 'age': user_age,
			'posts': Post.objects.filter(user=up), 
			'my_profile': (up.user.id == request.user.id)
		}, context_instance=RequestContext(request))

# View a user (via profile)
def user(request, user_id):
	up = get_object_or_404(UserProfile, user=user_id)
	return profile(request, up.id)

# Edit my profile
def edit_profile(request):
	newUser = False
	try:
		up = UserProfile.objects.get(user=request.user.id)
		form = UserProfileForm(request.POST or None, instance=up)
	except UserProfile.DoesNotExist:
		newUser = True
		form = UserProfileForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		user.user_id = request.user.id
		user.save()
		if newUser:
			messages.success(request, 'Your profile has been created, now check out what people like you have been posting:')
			return redirect('/')
		else:
			messages.success(request, 'Profile update saved.')
			return redirect('/userprofile/')
	return render_to_response('user/edit_profile.html', {
			'form': form
		}, context_instance=RequestContext(request))

posts/templates/user/detail.html
{% extends "base.html" %}
{% load mytags %}

{% block title %}- {{ userprofile }}{% endblock %}

{% block content %}
<h3>Jobshaker Profile</h3>
<div class="whitebox profile">
	<!--
	{% if userprofile.sex = 'F' %}
		<img src="/static/images/shutterstock_female.jpg" align="left" hspace="20" />
	{% endif %}
	{% if userprofile.sex = 'M' %}
		<img src="/static/images/shutterstock_male.jpg" align="left" hspace="20" />
	{% endif %}
	-->
	<p>
		<i>Nickname</i>
		<b>{{ userprofile }}</b>
	</p><p>
		<i>Profession</i>
		<b>{{ userprofile.profession }}</b>
	</p><p>
		<i>Details</i>
		{{ location }}
	</p><p>
		{% if age %}
			{{ age }} years, 
		{% endif %}
		{{ userprofile.get_sex_display }}
	</p><p>
		<i>Languages</i>
		{{ languages }}
	</p><p>
		<i>About me</i>
		{{ userprofile.aboutme|striptags|urlize|linebreaks }}
	</p>

	<p style="text-align:right">
		<a href="/" class="button small">Back to Board</a>
	{% if my_profile %}
		<a href="/accounts/edit/" class="button edit">Edit Profile</a>
	{% endif %}
	</p>

</div>
{% endblock %}

posts/templates/user/edit_profile.html
{% extends "base.html" %}
{% load url from future %}

{% block head %}
  {{ form.media }}
  <link href="/static/form.css" media="screen" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<div class="whitebox">
<form method="post" action="{% url 'posts.views.edit_profile' %}">{% csrf_token %}
<fieldset id="profileform">
	<legend>My profile</legend>
	<p></p>

	{% if form.errors %}
	<p class="error">There were errors in your profile, please have a look below and correct them.</p>
	{% endif %}

	<p>
		{{ form.profession.errors }}
		<label for="id_profession">Profession: 
		<span class="required">*</span></label>
		{{ form.profession }}
	</p><p>
		{{ form.postcode.errors }}
		<label for="id_postcode">Postcode:  
		<span class="required">*</span></label>
		{{ form.postcode }}
	</p>
	<div class="language">
		<b>Languages:</b>
		<p>	
			<label for="id_german">German:</label>
			{{ form.german }}
		</p><p>
			<label for="id_french">French:</label>
			{{ form.french }}
		</p><p>
			<label for="id_italian">Italian:</label>
			{{ form.italian }}
		</p><p>
			<label for="id_english">English:</label>
			{{ form.english }}
		</p><p>
			{{ form.other_lang.errors }}
			<label for="id_other_lang">Other:</label>
			{{ form.other_lang }}
		</p>
	</div>
	<p>
		{{ form.birth_year.errors }}
		<label for="id_birth_year">Year of birth:</label>
		{{ form.birth_year }}
	</p><p>
		{{ form.sex.errors }}
		<label for="id_sex">Sex:</label>
		{{ form.sex }}
	</p>
	<p class="note">
		Write a few words to make an impression with your profile,
		but do not share any personal identity details:
	</p><p>
		{{ form.aboutme.errors }}
		<label for="id_aboutme">About me:</label> 
		{{ form.aboutme }}
	</p>
	<center>
		<input class="btnCancel" type="reset" name="cancel" value="Cancel">
		<input class="btnSend" type="submit" name="submit" value="Save ">
	</center>
</fieldset>
</form>

</div>
{% endblock %}

posts/templates/user/replies.html
{% extends "base.html" %}
{% load mytags %}

{% block title %}- My Posts{% endblock %}

{% block content %}

<div class="twocolumn">
<h3>My Posts</h3>

<a href="/posts/new" class="newpost button" style="left:4px">New Post +</a>
	<br /><br />

{% for p in myposts %}
<div class="whitebox">
	<date>{{ p.pub_date }}</date><br>
	<a href="/posts/{{ p.id }}" class="intent">{{ p.intent }}</a>
	<ul class="replies">
	{% for reply in replies %}
		{% ifequal p.id reply.post.id %}
			<li>
				{% if reply.like %}
					<b>:)</b> 
				{% endif %}
				{% if reply.flag %}
					<b>:(</b> 
				{% endif %}
				<a href="/userprofile/{{ reply.user.id }}">{{ reply.user }}</a>:
				"{{ reply.comment }}"
			</li>
		{% endifequal %}
	{% endfor %}
	</ul>
</div>
{% endfor %}
{% if myposts|length == 0 %}
	<p class="notice">You haven't posted anything, why don't you 
	<a href="/posts/new">do that now</a>?</p>
{% endif %}
</div>

<div class="twocolumn">
<h3>My Replies</h3>

	<br /><br />

{% for p in replyposts %}
<div class="whitebox">
	<date>{{ p.pub_date }}</date><br>
	<a href="/userprofile/{{ p.user.id }}/">
	<b>{{ p.user }}</b></a> 
	is
	<a href="/posts/{{ p.id }}" class="intent">{{ p.intent }}</a>
	<ul class="replies">
	{% for reply in myreplies %}
		{% ifequal p.id reply.post.id %}
			<li>
				{% if reply.like %}
					<b>:)</b> 
				{% endif %}
				{% if reply.flag %}
					<b>:(</b> 
				{% endif %}
				<a href="/userprofile/{{ reply.user.id }}">{{ reply.user }}</a>:
				"{{ reply.comment }}"
			</li>
		{% endifequal %}
	{% endfor %}
	</ul>
</div>
{% endfor %}
{% if myreplies|length == 0 %}
	<p class="notice">You haven't replied yet, why not
	<a href="/">explore some more</a>?</p>
{% endif %}
</div>

{% endblock %}